---
 - name: Create User
   hosts: all
   gather_facts: False
   become: true

   vars:
     ansible_user: centos
     region: eu-central-1
     keypair: beegfs # pem file name

   tasks:

     - name: "Ensure Group Training exists"
       group:
         name: training
         state: present
         gid: 1002

     - name: "Add Training User"
       user:
         name: "training"
         shell: /bin/bash
         groups: training
     
     - name: Adduser training to sudoers filea
       lineinfile:
         path: /etc/sudoers
         regexp: '^training'
         line: 'training ALL=(ALL) NOPASSWD: ALL'
         validate: 'visudo -cf %s'

     - name: Allow Password login
       replace:
         path: /etc/ssh/sshd_config
         regexp: 'PasswordAuthentication yes'
         replace: 'PasswordAuthentication no'

     - name: Add new string 
       lineinfile:
         dest: /etc/ssh/sshd.config
         line:  '{{ item }}'
       with_items:
         - 'Match User training'
         - '    PasswordAuthentication yes'

     - name: Add hosts
       lineinfile:
         dest: /etc/hosts
         line: '{{ item }}'
       with_items:
         - '172.31.4.16  test-1-1'
         - '172.31.4.233 test-1-2'
         - '172.31.4.184 test-1-3'
         - '172.31.4.38  test-1-4'

     - name: Restart service sshd on centos, in all cases, also issue daemon-reload to pick up config changes
       ansible.builtin.systemd:
         state: restarted
         daemon_reload: yes
         name: sshd

     - name: change training user password
       user:
         name: training
         update_password: always
         password: "{{ newpassword|password_hash('sha512') }}"
